\documentclass{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage{hyperref}
\usepackage[margin=1in]{geometry}
\usepackage{booktabs}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}
% \SweaveOpts{concordance=TRUE}

\title{Results outline}
\author{Christophe Rouleau-Desrochers}
\date{\today}
\maketitle


% Set Wildchrokie species shortcut
\newcommand{\Ainc}{\textit{A. incana }}
\newcommand{\Ball}{\textit{B. alleghaniensis }}
\newcommand{\Bpap}{\textit{B. papyrifera }}
\newcommand{\Bpop}{\textit{B. populifolia }}

% Set CoringTreespotters species shortcut
\newcommand{\Arub}{\textit{A. rubrum }}
\newcommand{\Asac}{\textit{A. saccharum }}
\newcommand{\Afla}{\textit{A. flava }}
\newcommand{\Bnig}{\textit{B. nigra }}
\newcommand{\Cgla}{\textit{C. glabra }}
\newcommand{\Cova}{\textit{C. ovata }}
\newcommand{\Pdel}{\textit{P. deltoides }}
\newcommand{\Qalb}{\textit{Q. alba }}
\newcommand{\Qrub}{\textit{Q. rubra }}
\newcommand{\Tame}{\textit{T. americana }}   

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{verbatim}
##   year pgsGSL leafout coloredLeaves gdddiff pdsi tmeanmax tmeanmean tmeanmin
## 1 2016    156     124           280    1594 -4.0       29        23       17
## 2 2017    156     117           273    1472  1.6       27        22       16
## 3 2018    144     123           267    1569  1.9       28        23       17
## 4 2019    143     119           262    1549  4.0       28        22       17
## 5 2020    133     125           258    1645 -2.4       29        23       17
## 6 2021    144     116           260    1543  1.0       28        23       17
## 7 2022    137     121           258    1611 -2.7       29        23       17
## 8 2023    145     113           258    1459 -0.3       27        22       16
## 9 2024    134     118           252    1573  2.3       28        23       17
\end{verbatim}
\end{kframe}
\end{knitrout}

% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\section{Wildchrokie}
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>


%-------------------------------------------------------------------------------
\subsection{Growing season length and conditions}
%-------------------------------------------------------------------------------
\begin{enumerate}

% GSL length and conditions
\item 2020 was the shortest season by days (mean GSL $=$135.9),
with an average summer temperature of 
23.1$^\circ$C, and a summer thermal sum of 
1644.6 GDD. \\
2019 was the longest season by days (mean GSL $=$
141.5)
with an average summer temperature of 
22.4$^\circ$C, and a summer thermal sum of 
1549.4 GDD. \\
2018 had an average GSL of 138.7 days, 
an average summer temperature of 
22.9$^\circ$, and summer thermal sum of 
1569.5 GDD

% SOS conditions
\item Leafout dates across all years and species varied from 
112 (2019) to 
157 (2020) and budset date varied from 
225 (2018) to 
297 (2018), which are the two phases that set the boundaries of the growing season.

\item 2019 had the earliest start of season (mean leafout date $=$
121.7), and the coldest spring of the three years
(8.7$^\circ$C), with a spring thermal sum of 
491.1 GDD. \\
2020 had the latest start of season (mean leafout date $=$
141), 
and was also the warmest spring (
9.1$^\circ$C), but had the lowest thermal sum of three years (
458.1 GDD). \\
2018 had an average start of season of 127.3, an average spring temperature of
8.9$^\circ$, and the highest spring thermal sum (
511 GDD).

% SOS by species 
\item On average, the earliest leafout date was in 2019 for all species (\Ainc: 120.9, 
B alleghaniensis: 123, 
\Bpap: 125.8 and 
\Bpop: 121.5), and the latest was in 2020 (
\Ainc: 149.1, 
B alleghaniensis: 141.3, 
\Bpap: 136.6 and 
\Bpop: 133.9).
No species was consistently the earliest nor the latest to leafout.

% EOS condition
\item 2019 had the earliest end of season (mean budset date $=$ 263.2), and was coldest autumn (average autumn temperature $=$
8.7$^\circ$C), with a autumn thermal sum of
491.1 GDD. \\
2020 had the latest end of season (mean budset date $=$ 276.8), and was the warmest autumn (average autumn temperature $=$
9.1$^\circ$C) with the lowest thermal sum
(458.1 GDD). \\
2018 had an average end of season of 266, an average autumn temperature of 
8.9$^\circ$, 
and had the highest thermal sum of the three years (511 GDD).

% EOS by species 
\item On average, the earliest budset date was in 2019 for \Ainc 
(263.3) and 
\Ball (258), but in 2018 for
\Bpap (266.8) and 
\Bpop (266.3). 
The latest budset date for all species was in 2020
(\Ainc:280.9, 
\Ball:264.1, 
\Bpap:279.4 and 
\Bpop:282).
No species was consistently the earliest nor the latest to set buds.

% PDSI spring
\item The driest spring of the three years (MAM) (3-month averaged PDSI index) was
2020 with a PDSI value of 
1.3, and a cumulative precipitation of 
275.3 mm.
2019 was the least dry spring with a PDSI value of 
2.7 and a cumulative precipitation of 328.4 mm.

% PDSI summer
\item 2020 had the driest summer (JJA) with a PDSI value of 
-2.4, and a cumulative precipitation of 
199.1 mm.
2019 was the least dry summer with a PDSI value of 
4 and a cumulative precipitation of 
346 mm.

% Drought occurence
\item 2020 is the only year a with period of moderate drought ($PDSI [-3, -2]$) which was from 
June through 
August. Throughout the three years,
September of 
2020 was the only period with a severe drought ($PDSI < -3$) 

\end{enumerate}

%-------------------------------------------------------------------------------
\subsection{Ring widths}
%-------------------------------------------------------------------------------
\begin{enumerate}
\item The ring widths of our species vary from 0.4 mm to 13.5 mm. 
\item Ring widths for \Ball were the smallest and varied from 0.4 mm to 6.9 mm, and 
\Bpop had the largest rings which spanned from 
0.8 mm to 13.5 mm on average.
\Ainc (0.6 mm to 7.8 mm) and 
\Bpap were quite similar (0.7 mm to 6.4 mm).
\end{enumerate}

%-------------------------------------------------------------------------------
\subsection{Model results}
%-------------------------------------------------------------------------------

% Figure mu across all species and climate predictors
\begin{figure}[!ht]
\includegraphics[width=0.8\textwidth]{../../analyses/figures/growthModelsMain/muALLbspp.jpeg}
\caption{Model slope parameters across the different model predictors. GDD represent the accumulated growing degree days between leafout and budset, GSL the number of days between these phases. SOS represent the start of season, which is leafout and EOS, the end of season through budset. All predictors were fit using the same model and same observation, with only the independent variable changing (see Figure \ref{fig:wcSOSEOScomparison} for a comparison between two different data set length for SOS, and Figure \ref{fig:wcSOSEOScomparison}, for end of EOS). The dots represent the mean of the posterior distribution, the thick lines the 50\% uncertainty intervals (UI) and the thinner lines, the 90\% UI.}
\label{fig:wcmuplotbspp}
\end{figure}

\begin{enumerate}

% GDD
\item Growth did not change with greater thermal season for most species 
\Ainc: ($\beta = $ 0.1, $UI_{90}$[-0.1, 0.2]),
\Ball: ($\beta = $ 
0.1, $UI_{90}$[0, 
0.2], and
\Bpop:  ($\beta = $ 
0, $UI_{90}$[-0.2, 
0.2]].
However,
\Bpap grew more with longer thermal season ($\beta = $ 
0.3, $UI_{90}$[0, 
0.6])) (Figure \ref{fig:wcmuplotbspp} a) and e)).

% GSL
\item In contrast, most species grew more with longer calendar seasons 
(\Ainc: ($\beta = $ 0.1, $UI_{90}$[0.1, 0.2]),
\Ball: ($\beta = $ 0.1, $UI_{90}$[0, 0.2]) and
\Bpap: ($\beta = $ 0.3, $UI_{90}$[0.1, 0.5]).
Similarly to its response to the thermal season,
\Bpop did not grow more with longer calendar seasons ($\beta = $ 0, $UI_{90}$[-0.1, 0.1])
(Figure \ref{fig:wcmuplotbspp} b) and f).

% SOS
\item Growth decreased with a later start of season (SOS) for
\Ainc: $\beta = $ -0.1, $UI_{90}$[-0.2, -0.1]) and 
\Bpop ($\beta = $ -0.1, $UI_{90}$[-0.2, 0]), but didn't change for the other two 
(\Ball ($\beta = $ 0, $UI_{90}$[-0.1, 0]) and
\Bpap ($\beta = $ -0.1, $UI_{90}$[-0.2, 0])) (Figure \ref{fig:wcmuplotbspp} c) and g)). The estimates were unchanged when using the full or restricted datasets ($n =$239 vs $n=$227 Figure \ref{fig:wcSOSEOScomparison} (a)). 

% EOS
\item Growth decreased with a later end of season (EOS) only for for 
\Ainc ($\beta = $ -0.1, $UI_{90}$[-0.1, 0]). 
Growth did not change for the other species
(\Bpop: ($\beta = $ 0, $UI_{90}$[-0.1, 0], 
\Ball ($\beta = $ 0, $UI_{90}$[0, 0.1]) and
\Bpap ($\beta = $ 0.1, $UI_{90}$[0, 0.2]) (Figure \ref{fig:wcmuplotbspp} d) and g)). The estimates were unchanged when using the full or restricted datasets ($n =$230 vs $n=$227 Figure \ref{fig:wcSOSEOScomparison} (b)Figure \ref{fig:}). 

% Site
\item Growth did not change across any sites ( 
S. Hypolyte ($\alpha_{site} = $ 0.1, $UI_{90}$[-0.8, 0.9]),
D. College ($\alpha_{site} = $ -0.1, $UI_{90}$[-1, 0.7]), 
W. Mountains ($\alpha_{site} = $ 0.1, $UI_{90}$[-0.7, 1]) and 
H. Forest ($\alpha_{site} = $ = -0.1, $UI_{90}$[-1, 0.7]) 
(Figure \ref{fig:wcmuplotasite}))

% Wildchrokie site mu plot
\begin{figure}[!ht]
\includegraphics[width=1\textwidth]{../../analyses/figures/growthModelsMain/asiteMap.pdf}
\caption{The effect of sites on growth across a latitudinal gradient. a) Model intercept parameters for each site with growing degree days as the predictor. The dots represent the mean of the posterior distribution, the thick lines the 50\% uncertainty intervals (UI) and the thinner lines, the 90\% UI.}
\label{fig:wcmuplotasite}
\end{figure}

% Effect size on standardized scale
\item Across the four predictors the response was the strongest to 
SOS for
\Ainc ($\beta = $ 
-0.3, 
$UI_{90}$[-0.3, 
-0.2]) and 
\Bpop ($\beta = $ 
-0.2, 
$UI_{90}$[-0.3, 
0]),
GSL for 
\Ball ($\beta = $ 
0.1, 
$UI_{90}$[0, 
0.3]) and 
\Bpap ($\beta = $ 
0.4, 
$UI_{90}$[0.1, 
0.7])

\end{enumerate}

% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\section{CoringTreespotters}
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
%-------------------------------------------------------------------------------
\subsection{Species, years and observations}
%-------------------------------------------------------------------------------
\begin{enumerate}
\item CoringTreespotters includes eleven deciduous tree species with phenological observations from 2016 to 2024. In total, our final dataset has 239 leafout observations and 230. We used these observations to set the boundaries of individual-level growing seasons, which together yield 280 complete growing season lengths (GSL).
\end{enumerate}

%-------------------------------------------------------------------------------
\subsection{Growing season length and conditions}
%-------------------------------------------------------------------------------
\begin{enumerate}

% GSL length and conditions
\item Across our nine years, 2023  had the lowest summer thermal sum (1458.9 GDD), and 2020 had the highest summer thermal sum (1644.6 GDD).
\item 2020 was the shortest season by days (mean GSL $=$133.2),
with an average summer temperature of 
23.1$^\circ$C, and a summer thermal sum of 
1644.6 GDD. \\
2017 was the longest season by days (mean GSL $=$
156)
with an average summer temperature of 
21.5$^\circ$C, and a summer thermal sum of 
1471.7 GDD. \\

% SOS conditions
\item Leafout dates across all years and species varied from 
98 (2021) to 
136 (2020) and leaf colouring date varied from 
159 (2018) to 
311 (2016).

\item 2023 had the earliest start of season (mean leafout date $=$
113.5), an average temperature of (
10.1$^\circ$C), and a spring thermal sum of 
530.8 GDD. \\
2020 had the latest start of season (mean leafout date $=$
125.2), 
an average temperature of 
(9.1$^\circ$C), and a thermal sum of 
(458.1 GDD). This year coincides with the shortest growing season and had the fourth earliest EOS 258.4.\\

% SOS by species 
\item On average, the earliest leafout date for each species are
\Arub: 104 
(2023), 
\Asac: 111 
(2017), 
\Afla: 102.7 
(2016), 
\Ball: 104 
(2017), 
\Bnig: 108 
(2017), 
\Cgla: 110 
(2017), 
\Cova: 117.8 
(2020), 
\Pdel: 122.5 
(2018), 
\Qalb: 112 
(2017), 
\Qrub: 118.2 
(2020), 
\Tame: 109 
(2017), 

% EOS condition
\item 2024 had the earliest end of season (mean leaf colouring date $=$
251.8), an average temperature of (
13.1$^\circ$C), and an autumn thermal sum of 
531.1 GDD. \\
2016 had the latest end of season (mean leaf colouring date $=$
279.6), 
an average temperature of 
(13.2$^\circ$C), and an autumn thermal sum of 
(521.4 GDD). \\

% EOS by species 

% PDSI spring
\item The driest spring of the nine years (MAM) (3-month averaged PDSI index) was
2016 with a PDSI value of 
-3.3, a cumulative precipitation of 
223.5 mm.
2024 was the least dry spring with a PDSI value of 
2.9 and a cumulative precipitation of 408.5 mm.

% PDSI summer
\item 2016 also had the driest summer (JJA) with a PDSI value of 
-4, and a cumulative precipitation of 
151.2 mm.
2019 was the least dry summer with a PDSI value of 
4 and a cumulative precipitation of 
346 mm.

% Drought occurence
\item 2017, 2020, 2021, 2022, 2023 had at least one month of moderate drought ($PDSI [-3, -2]$) throughout their growing seasons.
Severe droughts periods occurred in 2016, 2017, 2020, 2022 was the only period with a severe drought ($PDSI < -3$) 

\end{enumerate}

%-------------------------------------------------------------------------------
\subsection{Ring widths}
%-------------------------------------------------------------------------------
\begin{enumerate}
\item The ring widths of our species---for the study period---vary from 0.4 mm to 11.7 mm. 
\item Ring widths for \Cova were the smallest and varied from 
0.7 mm to 
1.8 mm, and 
\Asac had the largest rings which spanned from 
0.4 to
11.1.
\end{enumerate}

%-------------------------------------------------------------------------------
\subsection{Model results}
%-------------------------------------------------------------------------------

% Figure mu across all species and climate predictors
\begin{figure}[!ht]
\includegraphics[width=0.8\textwidth]{/Users/christophe_rouleau-desrochers/github/coringtreespotters/analyses/figures/growthModelsMain/muALLbsppWlines.jpeg}
\caption{Model slope parameters across the different model predictors. GDD represent the accumulated growing degree days between leafout and budset, GSL the number of days between these phases. SOS represent the start of season, which is leafout and EOS, the end of season through budset. All predictors were fit using the same model and same observation, with only the independent variable changing (see Figure \ref{fig:wcSOScomparison} for a comparison between two different data set length for SOS, and Figure \ref{fig:tsSOSEOScomparison}, for end of EOS). The dots represent the mean of the posterior distribution, the thick lines the 50\% uncertainty intervals (UI) and the thinner lines, the 90\% UI.}
\label{fig:wcmuplotbsppTS}
\end{figure}

\begin{enumerate}

% GDD
\item Growth did not change with greater thermal season for most species 
(\Arub: $\beta = $ 0, $UI_{90}$[-0.2, 0.1],
\Asac: $\beta = $
0.1, $UI_{90}$[-0.1,
0.2],
\Afla: $\beta = $
0, $UI_{90}$[0,
0],
\Bnig: $\beta = $
0, $UI_{90}$[0,
0.1],
\Cgla: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Cova: $\beta = $
-0.1, $UI_{90}$[-0.2,
0],
\Pdel: $\beta = $
0, $UI_{90}$[-0.1,
0],
\Qalb: $\beta = $
0.1, $UI_{90}$[-0.2,
0.3],
\Qrub: $\beta = $
0, $UI_{90}$[-0.2,
0.2],
\Tame $\beta = $
0, $UI_{90}$[-0.1,
0]). 
However, growth for \Ball decreased with greater thermal season 
$\beta = $ -0.3, 
$UI_{90}$[-0.4,
-0.1])
) (Figure \ref{fig:wcmuplotbsppTS} a) and e)). These estimates were unchanged when using budburst instead of leafout as  the start of the growing season (Figure \ref{fig:buburstVSleafoutTS} (a))
 
% GSL
\item Similarly to the response to thermal season, the species did not increase growth with longer calendar season 
(\Arub: $\beta = $ 0.1, $UI_{90}$[-0.1, 0.2],
\Asac: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Afla: $\beta = $
0, $UI_{90}$[0,
0],
\Bnig: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Cgla: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Cova: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Pdel: $\beta = $
0, $UI_{90}$[-0.1,
0],
\Qalb: $\beta = $
0.1, $UI_{90}$[-0.1,
0.2],
\Qrub: $\beta = $
0, $UI_{90}$[-0.2,
0.1], and
\Tame: $\beta = $
0, $UI_{90}$[-0.1,
0]))
, including \Ball: $\beta = $
-0.1, $UI_{90}$[-0.2,
0] (Figure \ref{fig:wcmuplotbsppTS} b) and f)). These estimates were also unchanged when using budburst instead of leafout as  the start of the growing season (Figure \ref{fig:buburstVSleafoutTS} (b))

% SOS
\item Growth did not change in response to the start of season for any species
(\Arub: $\beta = $ -0.1, $UI_{90}$[-0.3, 0],
\Asac: $\beta = $
0, $UI_{90}$[0,
0.1],
\Afla: $\beta = $
0, $UI_{90}$[-0.2,
0.1],
\Ball: $\beta = $
-0.1, $UI_{90}$[-0.2,
0],
\Bnig: $\beta = $
0, $UI_{90}$[-0.1,
0],
\Cgla: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Cova: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Pdel: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Qalb: $\beta = $
-0.1, $UI_{90}$[-0.2,
0.1],
\Qrub: $\beta = $
0, $UI_{90}$[-0.1,
0.1], and
\Tame: $\beta = $
0.1, $UI_{90}$[0,
0.1])
(Figure \ref{fig:wcmuplotbsppTS} c) and g)). The estimates were unchanged when using the full or restricted datasets ($n =$321 vs $n=$280 Figure \ref{fig:tsSOSEOScomparison} (b)) (Figure*), nor when using budburst instead of leafout as  the start of the growing season (Figure \ref{fig:buburstVSleafoutTS} (c)).

% EOS
\item Similarly to the response to thermal season, the species did not increase growth with longer calendar season 
(\Arub: $\beta = $ 0, $UI_{90}$[-0.1, 0.2],
\Asac: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Afla: $\beta = $
0, $UI_{90}$[0,
0],
\Bnig: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Cgla: $\beta = $
0, $UI_{90}$[-0.1,
0.1],
\Cova: $\beta = $
0, $UI_{90}$[-0.1,
0],
\Pdel: $\beta = $
0, $UI_{90}$[-0.1,
0],
\Qalb: $\beta = $
0.1, $UI_{90}$[-0.1,
0.2],
\Qrub: $\beta = $
0, $UI_{90}$[-0.1,
0.1], and
\Tame: $\beta = $
0, $UI_{90}$[-0.1,
0]))
, except \Ball for which its growth decreased with later end of season ($\beta = $
-0.1, $UI_{90}$[-0.2,
0]) (Figure \ref{fig:wcmuplotbsppTS} d) and h)). The estimates were unchanged when using the full or restricted datasets ($n =$286 vs $n=$280 Figure \ref{fig:tsSOSEOScomparison} (b)).

% Effect size across species
\item 

\end{enumerate}
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
% Supplemental results
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\section*{Supplemental results}

\setcounter{table}{0}
\renewcommand{\thetable}{S\arabic{table}}
\setcounter{figure}{0}
\renewcommand{\thefigure}{S\arabic{figure}}

% Full vs restricted data comparison for Wildchrokie
\begin{figure}[!ht]
\includegraphics[width=1\textwidth]{../../analyses/figures/growthModelsMain/FullVSRestricted.jpeg}
\caption{Full vs most restricted rows of data for the model with SOS (a)) EOS (b)) as the predictor. Each pannel represent the different parameters used to fit the models.}
\label{fig:wcSOSEOScomparison}
\end{figure}

% Full vs restricted data comparison for Coringtreespotters
\begin{figure}[!ht]
\includegraphics[width=1\textwidth]{/Users/christophe_rouleau-desrochers/github/coringtreespotters/analyses/figures/growthModelsMain/FullVSRestricted.jpeg}
\caption{Full vs most restricted rows of data for the model with SOS (a)) EOS (b)) as the predictor. Each pannel represent the different parameters used to fit the models.}
\label{fig:tsSOSEOScomparison}
\end{figure}

% Leafout X climate predictors
\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/figures/climate/climSumLeafout.jpeg}
\caption{Leafout as a function of different climate predictors across winter (DJF) and spring (MAM). DJF is for December, January and February and MAM is for March, April and May. PDSI represents the Palmer Drought Severity Index averaged for each period. TempMeanMax, TempMeanMean and TempMeanMin are the averaged maximum, mean and mininimum monthly temperature over the 3-month periods. Precip is the total precipitation (mm) received over the 3-month periods.}
\label{fig:leafoutClim}
\end{figure}

% Budset X climate predictors
\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/figures/climate/climSumBudset.jpeg}
\caption{Budset as a function of different climate predictors across spring (MAM), summer (JJA) and autumn (SON). MAM is for March, April and May, JJA is for June, July and August and SON is for September, October and November. PDSI represents the Palmer Drought Severity Index averaged for each period. TempMeanMax, TempMeanMean and TempMeanMin are the averaged maximum, mean and mininimum monthly temperature over the 3-month periods. Precip is the total precipitation (mm) received over the 3-month periods.}
\label{fig:budsetClim}
\end{figure}

% Wildchrokie aspp mu plot
\begin{figure}[!ht]
\includegraphics[width=0.7\textwidth]{../../analyses/figures/growthModelsMain/muALLaspp.jpeg}
\caption{}
\label{fig:wcmuplotaspp}
\end{figure}

% Figure Growth X GDD
\begin{figure}[!ht]
\includegraphics[width=0.8\textwidth]{../../analyses/figures/growthModelsMain/growthModelSlopesperSppFacet.jpeg}
\caption{Ring width responses to total growing degree days (GDD) accumulated between the leafout and budset date. The length of the growing season is calculated between the leafout and budset date. The shaded areas represent the 50\% confidence intervals of the posterior distribution with measurement error, and the lines are their means. The dots represent the empirical data}
\label{fig:wcgrowthSlopesGDD}
\end{figure}

% Figure Growth X GSL
\begin{figure}[!ht]
\includegraphics[width=0.8\textwidth]{../../analyses/figures/growthModelsMain/growthModelSlopesperSppFacetGSL.jpeg}
\caption{Ring width responses to the length of the primary growing season (days). The length of the growing season is calculated between the leafout and budset date. The shaded areas represent the 50\% confidence intervals of the posterior distribution with measurement error, and the lines are their means. The dots represent the empirical data}
\label{fig:wcgrowthSlopesGSL}
\end{figure}

% Budburst vs leafout for CoringTreespotters
\begin{figure}[!ht]
\includegraphics[width=0.8\textwidth]{/Users/christophe_rouleau-desrochers/github/coringtreespotters/analyses/figures/growthModelsMain/budburstVSLeafout/DporousVSRporous.jpeg}
\caption{}
\label{fig:buburstVSleafoutTS}
\end{figure}

% Z-scored slope results Wildchrokie
\begin{figure}[!ht]
\includegraphics[width=0.8\textwidth]{../../analyses/figures/growthModelsMain/zscored/muALLbspp.jpeg}
\caption{}
\label{fig:bsppZscored}
\end{figure}

% Z-scored slope results CoringTreespotters
\begin{figure}[!ht]
\includegraphics[width=0.8\textwidth]{/Users/christophe_rouleau-desrochers/github/coringtreespotters/analyses/figures/growthModelsMain/zscored/muALLbspp.jpeg}
\caption{}
\label{fig:bsppZscoredTS}
\end{figure}

% % Climate variables
% <<climate_summary_table, results='asis', echo=FALSE>>=
% strCaption <- paste0("Climate variables for each year and seasons.")
% 
% print(xtable(climatesumfortable, 
%              digits  = c(0, 0, 0, 2, 2, 2, 2, 0),
%              caption = strCaption, 
%              label   = "tab:climate_summary"),
%       size               = "footnotesize",
%       include.rownames   = FALSE,
%       include.colnames   = FALSE,
%       caption.placement  = "top",
%       hline.after        = NULL,
%       sanitize.text.function = identity,
%       add.to.row = list(
%         pos     = list(-1, nrow(climatesumfortable)),
%         command = c(
%           paste("\\toprule \n",
%                 "Year & Season & PDSI & T\\textsubscript{max} ($^\\circ$C)",
%                 "& T\\textsubscript{mean} ($^\\circ$C)",
%                 "& T\\textsubscript{min} ($^\\circ$C)",
%                 "& PPT (mm) \\\\\n",
%                 "\\midrule \n"),
%           "\\bottomrule \n"
%         )
%       )
% )
% @

% Summer climate with phenology

% <<climatePhenoTS, results='asis', echo=FALSE>>=
% strCaption <- paste0("Summer climate with phenophases and season length coringTreespotters")
% 
% print(xtable(phenoclimatefortable, 
%              digits  = c(0, 1, 1, 1, 1, 1, 1, 1, 1),
%              caption = strCaption, 
%              label   = "tab:climatePhenoTS"),
%       size               = "footnotesize",
%       include.rownames   = FALSE,
%       include.colnames   = FALSE,
%       caption.placement  = "top",
%       hline.after        = NULL,
%       sanitize.text.function = identity,
%       add.to.row = list(
%         pos     = list(-1, nrow(climatesumfortable)),
%         command = c(
%           paste("\\toprule \n",
%                 "Year & GSL (days) & SOS (leafout date) & EOS (leaf colouring date)",
%                 "Summer thermal sum (GDD)",
%                 "PDSI",
%                 "& T\\textsubscript{max} ($^\\circ$C)",
%                 "& T\\textsubscript{mean} ($^\\circ$C)",
%                 "& T\\textsubscript{min} ($^\\circ$C)",
%                 "& PPT (mm) \\\\\n",
%                 "\\midrule \n"),
%           "\\bottomrule \n"
%         )
%       )
% )
% @

\end{document}
