\documentclass{article}
\usepackage{hyperref}
\usepackage[margin=1in]{geometry}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{gensymb}
\usepackage{natbib}

\begin{document}
% \SweaveOpts{concordance=TRUE}

\title{Manuscript outline}
\author{Christophe Rouleau-Desrochers}
\date{\today}
\maketitle

% Set Wildchrokie species shortcut
\newcommand{\Ainc}{\textit{A. incana}}
\newcommand{\Ball}{\textit{B. alleghaniensis}}
\newcommand{\Bpap}{\textit{B. papyrifera}}
\newcommand{\Bpop}{\textit{B. populifolia}}

% Set CoringTreespotters species shortcut
\newcommand{\Arub}{\textit{A. rubrum}}
\newcommand{\Asac}{\textit{A. saccharum}}
\newcommand{\Afla}{\textit{A. flava}}
\newcommand{\Bnig}{\textit{B. nigra}}
\newcommand{\Cgla}{\textit{C. glabra}}
\newcommand{\Cova}{\textit{C. ovata}}
\newcommand{\Pdel}{\textit{P. deltoides}}
\newcommand{\Qalb}{\textit{Q. alba}}
\newcommand{\Qrub}{\textit{Q. rubra}}
\newcommand{\Tame}{\textit{T. americana}}   

% 
% \begin{figure}[h!]
% \includegraphics[width=0.85\textwidth]{../../notes/chaptersDesign/chaptersDesign.pdf}
% \caption{Overview of the age class, species, provenance of the trees used in each study along with the type of study each project consists of. The colored lines represent the period of the growth data and the shaded areas are the phenological data. Both are colour-coded by project. Each phylogram illustrates the species used in each project. The map illustrates the four different provenances used in Wildchrokie, and the star represents the location of Wildchrokie and CoringTreespotters.}
% \label{fig:chaptersDesign}
% \end{figure}

% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\section*{Introduction}
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\begin{enumerate}


% plug this somewhere: while warmer spring temperatures trigger the onset of cell production, it alone doesnt increase wood prod with water playing. amore decisive role on wood prod (Wang2025Seasonal)
% Paragraph 1
\item The most frequently observed biological impact of climate change is major changes in phenology \citep{parmesan_globally_2003,cleland_shifting_2007,lieth_phenology_1974,woolway_phenological_2021,menzel_european_2006}
  \begin{enumerate}
  
  \item Shifts in spring and autumn phenology modifies when seasons start and end \citep{duputie_phenological_2015}.
  
  \item Understanding the consequences of these shifts requires understanding how much and why growing seasons have changed \citep{duputie_phenological_2015}.
  
  \item Spring phenology advances, \citep{wolfe_climate_2005,chmielewski_response_2001,fu_recent_2014} driven by temperature \citep{chuine_why_2010,cleland_shifting_2007,penuelas_responses_2001}
  
  \item Autumn phenology delays, but much less than spring \citep{gallinat_autumn_2015,jeong_macroscale_2014} and driven by temperature and photoperiod \citep{cooke_dynamic_2012,flynn_temperature_2018,korner_phenology_2010,delpierre_temperate_2016}
  
  
  \end{enumerate}
  
% Paragraph 2
\item Shifts in spring and autumn phenology supports the assumption that longer growing seasons increase tree growth \citep{keenan_net_2014, stridbeck_partly_2022}
  \begin{enumerate}
  
  \item Recent research shows that this may not be the case \citep{dow_warm_2022,green_limits_2022,silvestro_longer_2023,wang_seasonal_2025,matula_shifts_2023,wang_seasonal_2025}
  
  \item \cite{dow_warm_2022} showed that trees did not grow more or faster despite warmer and earlier springs at the regional scale
  
  \item \cite{Cabon2022Cross} showed a decoupling between GPP and carbon storage at the global scale.
  
  \item If trees don't grow as we expect, it could affect forest carbon cycle projections \citep{richardson_climate_2013,swidrak_comparing_2013} and subsequent climate solutions \citep{green_limits_2022}
  
  \end{enumerate}
  
% Paragraph 
\item Understanding these finds requires answering why trees do not grow more despite longer growing seasons.
  \begin{enumerate}
  
  \item We have a poor understanding of carbon allocation to above-ground biomass, despite it being one of the largest carbon sink \citep{cabon_cross-biome_2022}.
  
  \item Linear representation of growth as a function of carbon assimilation is wrong \citep{cabon_cross-biome_2022}
  
  \item Trees may be source or sink limited, which emphasizes the importance of understanding the temperature sensitivity relationship between growth and photosynthesis \citep{gessler_beyond_2024}.
  
  \item Growth may be more sensitive to varying environmental conditions than photosynthesis, which could mislead models \citep{cabon_cross-biome_2022,cabon_water_2020,muller_water_2011,peters_turgor_2021}
  
  \item Hard nature of climate change makes understanding the internal physiological and external constraints to growth critical \citep{almagro_longterm_2025,cabon_cross-biome_2022,wolkovich_why_2025}
  \end{enumerate}

% Paragraph 
\item How trees internal programming and their susceptibility to environmental conditions could constrain their growth?
  \begin{enumerate}
  \item Growth as any other biological mechanism is genetically controlled, and will thus vary by species \citep{howe_genotype_2003,wolkovich_why_2025, silvestro2025From}
  
  \item Tree plasticity is a highly variable trait that changes with species' life history strategies \citep{cuny_couplings_2019,michelot_comparing_2012}, affecting how flexible their growth is in response to varying environmental conditions.
  
  \item While CO2 concentrations increased, drought, heat waves, competition, insect outbreaks and spring frosts---factors projected to change in frequency and severity with a warming climate---can offset the benefits of longer seasons \citep{tyree_xylem_2002, choat_triggers_2018, li_widespread_2023,trenberth_global_2014,intergovernmental_panel_on_climate_change_detection_2014,chiang_evidence_2021,polgar_leafout_2011,reinmann_compensatory_2023}.
  
  \item Droughts can act as a severe growth constraint \citep{kang_earlier_2023} by stopping growth early \citep{dox_severe_2022} or inducing tissue mortality \citep{li_widespread_2023}.
  
  \item Intra- and inter-specific competition for nutrients, water and light can also offset a tree's capacity to take advantage of extra days in the season \citep{cleland_effects_2024}.

  \end{enumerate}
  
% Paragraph 
\item Understanding the constraints to growth requires defining the growing season and growth.
  \begin{enumerate}
  
  \item Different definitions of GS: we propose to use calendar (number of days) and thermal season (window of opportunity of thermally favorable meteorological conditions for plant growth) \citep{korner_four_2023}
  
  \item The calendar season only accounts for the number of days in the season as the predictor for growth, implying a stable growth rate throughout the season. 
  
  \item This may reveal a role of some neglected cooler and shorter days in the season that have a weak influence on the thermal season.
  
  \item Growth rate changes with temperature, which the thermal season accounts for and should therefore better predict growth responses.
  
  \item Wood formation (xylogenesis) is the allocation of carbon for long-term storage \citep{etzold_number_2022,silvestro_roots_2025}, and the radial growth increments are represented through tree rings \citep{plomion_wood_2001}
  
  \item Allometries using tree DBH and height have a coarse temporal scale and can miss extreme events affecting growth  \citep[e.g.,][]{meyer_mathematical_1940,saunders_height-diameter_2008}.
  
  \item Tree rings are more precise growth proxies, which we use here \citep{gazol_forest_2018,manzanedo_towards_2019}
  
  \end{enumerate}
  
% Paragraph 
\item Growth drivers differences across species need to be considered.
  \begin{enumerate} 
  
  \item Phenology and the relationship between growth and growing season length varies heavily across species \citep{etzold_number_2022}
  
  \item Pooling all species together in carbon sequestrations models is a weakness \citep{green_limits_2022,cabon_cross-biome_2022,wolkovich_why_2025}
  
  \item We propose to use ground-based leaf phenology observations across several species to address this issue \citep{piao_plant_2019}
  
  \item These observations provide valuable insights of the growth temporality of trees not suitable for experimental trials \citep{wolkovich_why_2025}
  
  \item Cambial phenology in diffuse-porous trees is closely synchronized with leaf phenology \citep{marchand_timing_2021,silvestro_roots_2025,suzuki_phenological_1996}, so we can use them to as a reliable proxy for start and end of the growing season \citep{stridbeck_partly_2022} 
  
  \end{enumerate}
  
\item Local adaptation could inform growth responses of species under future climate change \citep{soolanayakanahally_timing_2013,wolkovich_why_2025}.
  \begin{enumerate} 
  \item Provenance refers to the geographic and climatic origin of a population \citep{aitken_time_2016,housset_tree_2018}
  
  \item Trees from northern provenances sometimes have later start of season phenology \citep{zeng_weak_2024} and often earlier end of season phenology=shorter growing season \citep{way_photoperiod_2015,vitasse_interaction_2014}.
  
  \item This is especially true for budset---which marks the end of primary growth---, with its phenotypic variance being strongly related to provenance and photoperiod acting as the primary cue \citep{aitken_time_2016,soolanayakanahally_timing_2013,way_photoperiod_2015}.
  
  \item Thus, common gardens with provenances across a latitudinal gradient can inform tree's growth responses to future climatic conditions.
  
  \end{enumerate} 

% Paragraph 6
\item To answer if trees grow more with longer growing seasons, we related three years of leaf phenology and growth data across four species and four provenances in a common garden on juvenile trees. Our objectives are:
  \begin{enumerate}
  \item Determine if trees grow more with longer thermal vs calendar season (ref: conceptual figure).
  \item Understand the calendar growing season relationship with growth and how it relates to the SOS and EOS.
  \item Determine how growth changes across years, provenances and individual trees.
  \end{enumerate}
\end{enumerate}

% Conceptual figure
\begin{figure}[!ht]
\includegraphics[width=1\textwidth]{../../analyses/figures/climate/gsconceptualfig.jpeg}
\caption{We show how shifting growing season length with climate change affects both the temperature experienced during the growing season. (a) The Boston airport Climate station smoothed curve mean daily average 1945-1965 (blue) and 2005-2025 (red) to represent the changes in temperature before and after significant climate warming that increased in the 1980s. With climate change, spring events have advanced and fall phenology has delayed, but to much lesser extent (represented through the arrows), this lengthened the calendar growing season, but concurently changed the temperature trees experience early in their season }
\label{fig:wcmuplotayear}
\end{figure}

% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\section*{Results}
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
Separate document

% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\section*{Discussion}
% <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\begin{enumerate}
\item What we did, how we did it and what we found
  \begin{enumerate}
  
  \item We used 81 juvenile trees of four species across four provenances to understand if longer growing seasons using leaf phenology increased growth using tree rings
  
  \item We found that longer growing seasons increased growth for all species, but varied depending on the metric 
  
  \item Thermal season was a better predictor for growth than the calendar season
  \end{enumerate}

\item Thermal season being a better predictor than the calendar season may be caused by it weighting the relative importance of the days on growth better than the calendar season
  \begin{enumerate}
  
  \item Growth rate follows a temperature response curve, thus trees don't grow at the same speed all year round
  
  \item Cool and short spring days count for less in the thermal season compared to the calendar season where each day counts the same
  
  \end{enumerate}
  
\item Disentangling the calendar season with the start and end of season may reveal something...
  \begin{enumerate}
  \item 123
  \end{enumerate}

\item Our trees grew more with longer seasons in absence of external constraints
  \begin{enumerate}
  \item Droughts can strongly impact tree growth, thus when seasons are longer, but not drier, trees just may be able to fully take advantage of these extra days
  \item Earlier spring means trees start water uptake earlier, which may increase the severity of droughts later in the season
  \item Dow showed that growth and growing season length are decoupled in a natural system where trees compete for water, but also for light and nutrients
  \item Though we did not control for nutrients, our study design allowed us to control for light availability where taller trees did not shade the others at the life stage we looked at
  \item The timing of phenological phases are shifting and this will affect inter-specific competition for resources, this higlights the importance of accounting for competition when adressing this question
  \end{enumerate}

\item Our species have different life history strategies and this may inform how they respond to growing season length
  \begin{enumerate}
  \item 123
  \end{enumerate}

\item We found little effect of provenance, suggesting local adaption on growth may be weak under current conditions
  \begin{enumerate}
  \item 123
  \end{enumerate}

\item Our study has limitations
  \begin{enumerate}
  \item We had low sample size and not individuals for each provenance for all species 
  \item We didn't account for extreme temperatures in our models, though there was no extended heat wave periods throughout the study
  \end{enumerate}
  
\item Our results highlights the importance of accounting for 
  \begin{enumerate}
  \item 123
  \end{enumerate}
  
\end{enumerate}
%<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
% REFERENCES %
%<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\bibliography{ExportedItems}
\bibliographystyle{nature} 

%<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
% Supplement %
%<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\clearpage
\section*{Supplemental results}

\setcounter{table}{0}
\renewcommand{\thetable}{S\arabic{table}}
\setcounter{figure}{0}
\renewcommand{\thefigure}{S\arabic{figure}}

\end{document}